[package]
name = "usd-jpy-converter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ujcon"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
